### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by zuurw** [subatomicglue/musicserver#1]
Hello, Im a Graphic Designer that likes to contribute to open source projects, specilly in music projects, I would like to know if you need a logo for you project? I would like to work with you.

If you want just tell me what you want for the logo?

Greetings

**Comment by subatomicglue** [comment]
Could be interesting.  You can see it’s early, no branding yet.  Any ideas?  If you have something good we can apply it here... no promises of course

Post your ideas

Or here are some ideas
- demon
- monkey
- Cthulhu 
- sunburst
- treefrog
- bug (or bug face)

**Comment by zuurw** [comment]
That´s nice ideas, I will star to design something today, when I have something I will show to you.

Cheers!

**Comment by zuurw** [comment]
Hello, I create this design for the "Treefrog", I create also de black & white versions and I think they look really good.

I can change the colors of the logo if you want.

Send me your feedback.

Best Regards

![treefrog logo proposal](https://user-images.githubusercontent.com/40801473/42269708-c9f2e83e-7f76-11e8-80c2-ee1eca36edae.png)

**Comment by subatomicglue** [comment]
It’s  a good start.  It is cute, in a good way.   Here is my critique, I hope it is constructive.

It’s a little busy, the head, the hands, the tree branch, offset to one side (not symmetric).  I think symmetry could help.

The black and white version feels a little empty, with the thinner lines there (like a line drawing in a coloring book).   I'd like to see the white/black balanced a little more, an idea is to alternate 'coloring' of white/black in the spaces (pupils is an easy one) to balance the image a little more - so that there are bigger chunks of those tones.   The pupils could also be bigger to help balance, look more cute, etc.  Nose holes could be solid instead of circles, another way to simplify and remove some of that "line drawing" style.

Ideas
- try a version with just the head (like my github mantis logo)
- try a version focusing on the interesting frog hand.  Keep it simple
- try a version with both face and hand(s) but without the branch.  I wonder if the branch complicates the image needlessly.  Thinking like the [Starbucks logo](https://png.icons8.com/color/1600/starbucks.png).  There is the mermaid face, but also the “legs” wrapping around in a circle.  Whole thing is very symmetric / balanced.
- try both two color version, as well as 3-4.  Without gradient.  Can it work.  To me this indicates good separation of the image structure .   For treefrogs:  orange hands, white underbody/chin/eye-rims, green head/body, red eyes, black pupils.  There's a lot of color for sure!  Challenging for sure.   But we can create a fantasy frog, and play with the colors a bit.
- might look less cluttered without the circle.  Maybe the round is competing with the straight branch
- some anime styling (see mantis) applied to the frog...  big cute eyes, etc...

See my logo for github, it’s a little more like what I’m thinking for a logo:  zoomed a little closer, focused on one part (face), and symmetry/balance in the image.

I’m thinking about having the ability to generate 16x16 px icons out of this, so simplicity helps that.  Also my aesthetic in logodesign is the simpler the better, easy to make monochrome as your main logo.  Easier to use solid colors instead of gradients

**Comment by subatomicglue** [comment]
Big pupils are nice, [reference](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwisnOTOq4bcAhVF3IMKHWsfCjsQjRx6BAgBEAU&url=https%3A%2F%2Fwww.gettyimages.com%2Fphotos%2Fred-eyed-tree-frog&psig=AOvVaw0ze1Mcz7nEwQL8GZdaTZrE&ust=1530824369426862)

**Comment by subatomicglue** [comment]
Big pupils are nice, [reference](https://media.gettyimages.com/photos/redeyed-tree-frog-these-agalychnis-callidryas-picture-id763161757?s=612x612)

**Comment by subatomicglue** [comment]
Exaggerated head/eyes & compositional centering of hands under the head, [reference](http://images.mentalfloss.com/sites/default/files/istock_000003319805_small.jpg)

**Comment by subatomicglue** [comment]
Smiling frog [reference](https://media.mnn.com/assets/images/2016/09/tree-frog.jpg.600x315_q80_crop-smart.jpg)

**Comment by subatomicglue** [comment]
Frog with headphones could be awesome for a music server. :)
Which, doing a quick search, lol, there is some [reference](https://www.walmart.com/ip/Gecko-Tree-Frog-with-Headphones-Music-Lover-Black-33-in/432201749)...  Which I think we could do better (cartoonify, simplify, anime, etc...)

**Comment by zuurw** [comment]
Ok, I will try to design something with all your requests.

**Comment by zuurw** [comment]
What do you think abou this face?

![facefrog](https://user-images.githubusercontent.com/40801473/42339067-c844d872-8083-11e8-9153-8febb74730fe.png)

**Comment by subatomicglue** [comment]
cool, but the eyes are too much forward, like primates or dogs or cats.   

frogs seem to have their eyes on the sides, like my mantis logo, and also like this [reference](http://images.mentalfloss.com/sites/default/files/istock_000003319805_small.jpg).

**Comment by zuurw** [comment]
![frog2](https://user-images.githubusercontent.com/40801473/42369835-047ab1de-8103-11e8-8647-843dbd1711e3.png)

**Comment by subatomicglue** [comment]
Cool.  Back from vacation now.  Hmm. Feels like there is no chin. Maybe do a slightly open mouth?

**Comment by zuurw** [comment]
Hi @subatomicglue, how are you? how were your vacations?

I will try to make an open mouth.

Cheers!

**Comment by zuurw** [comment]
![final](https://user-images.githubusercontent.com/40801473/43041060-049b0e9c-8d4d-11e8-9eee-efcab809be04.png)

**Comment by subatomicglue** [comment]
Cool looking good.  I like the first one with wide smile and tongue.   

Should we play with giving it teeth?  Like the evil Spider-Man (Venom)?  https://goo.gl/images/NNQRm1

**Comment by zuurw** [comment]
Hi @subatomicglue, for that I have to change again the mouth. I think frogs dont have teeth :)
